require("functions")
vim.keymap.set({ "i", "v", "t" }, "©", "<Esc>", { desc = "Open parent directory" })
vim.keymap.set("n", "<C-e>", "<CMD>Oil<CR>", { desc = "Open parent directory" })
vim.keymap.set({ "n" }, "gw", HotToGo, { noremap = true, silent = true })
vim.keymap.set("i", "<A-m>", InsertPrint, { noremap = true, desc = "personal: printfc" })
vim.keymap.set("n", "<A-m>", "", { noremap = true, desc = "personal: printfc" })
vim.keymap.set({ "n" }, "<A-m>", "<Esc>mpyyp`pj", { noremap = true, desc = "Nya" })
vim.keymap.set({ "v" }, "<A-m>", "mzy`]p`zj", { noremap = true, desc = "Nya" })
vim.keymap.set({ "n", "x" }, "ge", "$", { noremap = true, desc = "Nya" })
vim.keymap.set({ "v" }, "ge", "$h", { noremap = true, desc = "Nya" })
vim.keymap.set({ "n", "x", "v" }, "gs", "_", { noremap = true, desc = "Nya" })
vim.keymap.set(
	"n",
	"gl",
	"<cmd>lua vim.diagnostic.open_float()<CR>",
	{ desc = "personal: show diagnostics", noremap = true, silent = true }
)
vim.keymap.set("n", "<leader>a", "<c-^>", { desc = "alternate file", noremap = true, silent = true })
vim.keymap.set("n", "<A-s>", SaveAll, { desc = "alternate file", noremap = true, silent = true })
vim.keymap.set("n", "<leader><cr>", "<cmd>wqa!<cr>", { desc = "alternate file", noremap = true, silent = true })
-- vim.keymap.set({ "n" }, "<C-h>", "<c-w>h", { noremap = true, desc = "left split" })
-- vim.keymap.set({ "n" }, "<C-l>", "<c-w>l", { noremap = true, desc = "right split" })
-- vim.keymap.set({ "n" }, "<C-k>", "<c-w>k", { noremap = true, desc = "up split" })
-- vim.keymap.set({ "n" }, "<C-j>", "<c-w>j", { noremap = true, desc = "down split" })
vim.keymap.set({ "n" }, "<leader>;", "<cmd>nohls<cr>", { noremap = true, desc = "no high" })
vim.keymap.set({ "n" }, "<c-n>", "<cmd>cn<cr>", { noremap = true, desc = "no high" })
vim.keymap.set({ "n" }, "<c-p>", "<cmd>cp<cr>", { noremap = true, desc = "no high" })
vim.keymap.set({ "n", "v" }, "<", "<gv", { noremap = true, desc = "no high" })
vim.keymap.set({ "n", "v" }, ">", ">gv", { noremap = true, desc = "no high" })
vim.keymap.set("v", "<A-j>", ":m '>+1<CR>gv=gv")
vim.keymap.set("v", "<A-k>", ":m '<-2<CR>gv=gv")
vim.keymap.set("n", "<A-k>", "<cmd>m .-2<CR>==")
vim.keymap.set("n", "<A-j>", "<cmd>m .+1<CR>==")
function diagnostic()
	vim.diagnostic.enable(not vim.diagnostic.is_enabled())
end
vim.keymap.set({ "n" }, "<leader>d", diagnostic, { noremap = true, desc = "replacement in selection" })
-- Toggle compiler results
vim.keymap.set("n", "<A-c>", CompilerModeChafoide)
vim.keymap.set("n", "©", CompilerModeChafoide)

vim.keymap.set("n", "<C-c>", "<cmd>ccl<CR>")
vim.keymap.set("n", "<leader>rn", function()
	-- it returns success status, thus you can fallback like so
	if not require("ts-autotag").rename() then
		vim.lsp.buf.rename()
	end
end)
vim.keymap.set("n", "<leader>q", "<cmd>q!<CR>")
vim.keymap.set("n", "<leader>Q", "<cmd>qa!<CR>")
-- vim.keymap.set("n", "gd", vim.lsp.buf.definition, opts)
vim.keymap.set({ "n", "v", "x" }, "<leader>n", ":norm ", { desc = "enter norm command." })
vim.keymap.set({ "n" }, "<leader>rf", ":%s//&", { desc = "enter replace whole file" })
vim.keymap.set({ "v", "x" }, "<leader>rs", ":s//&", { desc = "enter replace selection" })
vim.keymap.set({ "n" }, "<leader>/", ":%s/", { desc = "enter replace selection" })
vim.keymap.set({ "v", "x" }, "<leader>/", ":s/", { desc = "enter replace selection" })
vim.keymap.set({ "n" }, "*", "mT*`T", { desc = "enter replace selection", noremap = true })

vim.keymap.set({ "n", "v", "x" }, "<leader>b", ":b ", { desc = "enter norm command." })
vim.keymap.set({ "n", "v", "x" }, "<leader>O", "<cmd>Oil ./<CR>", { desc = "open oil at project root" })
vim.keymap.set({ "n", "v", "x" }, "<leader>o", ":Oil ./", { desc = "enter oil command." })
vim.keymap.set("n", "<leader>t", ":$tabnew<CR>", { noremap = true })
-- vim.keymap.set("n", "<leader>c", ":tabclose<CR>", { noremap = true })
vim.keymap.set("n", "<leader>n", ":tabn<CR>", { noremap = true })
vim.keymap.set("n", "<leader>p", ":tabp<CR>", { noremap = true })
vim.keymap.set("n", "<leader>1", "1gt", { noremap = true })
vim.keymap.set("n", "<leader>2", "2gt", { noremap = true })
vim.keymap.set("n", "<leader>3", "3gt", { noremap = true })
vim.keymap.set("n", "<leader>4", "4gt", { noremap = true })
vim.keymap.set("n", "<leader>l", "g<Tab>", { noremap = true })
-- move current tab to previous position
-- move current tab to next position
vim.keymap.set("n", "<leader>mtp", ":-tabmove<CR>", { noremap = true })
vim.keymap.set("n", "<leader>mtn", ":+tabmove<CR>", { noremap = true })
vim.keymap.set({ "n", "v", "x" }, "ga", "<Plug>(EasyAlign)")
vim.keymap.set("n", "<leader>g", GDLVBreak, { noremap = true })
vim.keymap.set("v", "<leader>s", '"by:s/b/', { noremap = true })
vim.keymap.set("n", "dA", "V%d", { noremap = true })
vim.keymap.set("n", "cA", "V%c", { noremap = true })
vim.keymap.set({ "n" }, "ds", '"_dw', { noremap = true })
vim.keymap.set({ "v" }, "D", '"_d', { noremap = true })
vim.keymap.set({ "n" }, "dS", '"_dd', { noremap = true })
vim.keymap.set({ "n", "v", "x" }, "<leader>w", '"wdiw', { noremap = true })
vim.keymap.set({ "n", "v", "x" }, "<leader>W", '"wdW', { noremap = true })
vim.keymap.set({ "n", "v", "x" }, "<c-y>", '"Ay', { noremap = true })
vim.keymap.set({ "n", "v", "x" }, "<leader>Y", "qaq", { noremap = true })
vim.keymap.set({ "n" }, "<leader>Z", "<cmd>vs#<CR>", { noremap = true })
-- vim.keymap.set({ "n", "v" }, "<c-m>", "::<CR>", { noremap = true })
vim.keymap.set({ "v" }, "x", "<Plug>(Exchange)", { noremap = true })
vim.keymap.set({ "n" }, "<C-w>sk", "<C-w>s<C-w>k", { noremap = true })
vim.keymap.set({ "n" }, "<C-w>sj", "<C-w>s<C-w>j", { noremap = true })
vim.keymap.set({ "n", "v", "x" }, "<leader>l", ":lua<CR>", { noremap = true })
vim.keymap.set("t", "<Esc>", "<C-\\><C-n>", { silent = true, noremap = true })
vim.keymap.set("i", "<A-c>", "<Esc>", { silent = true, noremap = true })
vim.keymap.set("n", "gd", vim.lsp.buf.definition, opts)
vim.keymap.set("n", "<leader>A", ":wincmd v <cr><c-^>", { desc = "alternate file", noremap = true, silent = true })
vim.keymap.set("n", "<leader><Tab>", "g<Tab>", { desc = "alternate tab", noremap = true, silent = true })
-- try all of these in order
vim.keymap.set("n", "du", "dt{", { desc = "alternate tab", noremap = true, silent = true })
vim.keymap.set("n", "du", "dt,", { desc = "alternate tab", noremap = true, silent = true })
vim.keymap.set("n", "<F1>", "mFggVGgq`F", { desc = "alternate tab", noremap = true, silent = true })
vim.keymap.set("n", "du", "dt(", { desc = "alternate tab", noremap = true, silent = true })

-- vim.keymap.set(
-- 	"n",
-- 	"<F8>",
-- 	":wincmd s<CR><cmd>e _____output_____.sh <CR><cmd>%d<CR>:r! ",
-- 	{ desc = "alternate tab", noremap = true }
-- )
-- vim.keymap.set("n", "<leader>c", function()
-- 	Emacmds("_____output_____.sh")
-- end, { desc = "alternate tab", noremap = true })
vim.keymap.set("n", "<leader>c", ":! ", { desc = "alternate tab", noremap = true })
vim.keymap.set("v", "S", "y:S/+//g<Left><Left>", { desc = "alternate tab", noremap = true })
vim.keymap.set("v", "R", "y:%S/+//g<Left><Left>", { desc = "alternate tab", noremap = true })
vim.keymap.set("n", "<CR>", "gF", { desc = "alternate tab", noremap = true })
