set -a terminal-features "tmux-256color:RGB"
set -g prefix C-SPACE
set -g base-index 1
set -g renumber-windows on   
set -g mode-keys vi
set -g status-position top
set -g status-justify absolute-centre
set -g status-style "fg=red"
set -g window-status-current-style "bold fg=#ece1d7 bg=#fa9ebc"
set -g status-interval 5
set -g repeat-time 18000
set -g status-left "#S"
set -g status-right ""

bind r source-file "~/dotfiles/tmux/tmux.conf"
bind b set -g status
bind-key -n M-BSpace send-keys C-w
# bind f run "tmux neww ~/.config/scripts/tmux-session-dispensary.sh"
# bind g run "~/.config/scripts/open-github.sh"
# bind t run "tmux neww ~/.config/scripts/time.sh"
# bind N run "~/.config/scripts/tmux-session-dispensary.sh ~/documents/notes"
# bind P run "~/.config/scripts/tmux-session-dispensary.sh ~/documents/projects"
# bind D run "~/.config/scripts/tmux-session-dispensary.sh ~/.config"
# bind H run "~/.config/scripts/tmux-session-dispensary.sh ~"
# bind S run "~/.config/scripts/tmux-session-dispensary.sh ~/documents/projects/stormy"
# bind G neww -n "git" -S lazygit
bind E show-environment -g
bind  c  new-window      -c "#{pane_current_path}"
bind  %  split-window -h -c "#{pane_current_path}"
bind '"' split-window -v -c "#{pane_current_path}"
is_vim="ps -o state= -o comm= -t '#{pane_tty}' | grep -iqE '^[^TXZ ]+ +(\\S+\\/)?g?\.?(view|n?vim?x?)(-wrapped)?(diff)?$'"

bind-key -n 'C-S-h' if-shell "$is_vim" 'send-keys C-h' { if -F '#{pane_at_left}' '' 'select-pane -L' }
bind-key -n 'C-S-j' if-shell "$is_vim" 'send-keys C-j' { if -F '#{pane_at_bottom}' '' 'select-pane -D' }
bind-key -n 'C-S-k' if-shell "$is_vim" 'send-keys C-k' { if -F '#{pane_at_top}' '' 'select-pane -U' }
bind-key -n 'C-S-l' if-shell "$is_vim" 'send-keys C-l' { if -F '#{pane_at_right}' '' 'select-pane -R' }
bind-key -T copy-mode-vi 'v' send -X begin-selection
bind-key -T copy-mode-vi 'r' send -X rectangle-toggle
bind-key -T copy-mode-vi 'y' send -X copy-pipe-and-cancel

bind-key -T copy-mode-vi 'C-h' if -F '#{pane_at_left}' '' 'select-pane -L'
bind-key -T copy-mode-vi 'C-j' if -F '#{pane_at_bottom}' '' 'select-pane -D'
bind-key -T copy-mode-vi 'C-k' if -F '#{pane_at_top}' '' 'select-pane -U'
bind-key -T copy-mode-vi 'C-l' if -F '#{pane_at_right}' '' 'select-pane -R'
bind-key -T copy-mode-vi 'C-n' if -F '#{window_end_flag}' '' 'select-window -n'
bind-key -T copy-mode-vi 'C-p' if 'test #{window_index} -gt #{base-index}' 'select-window -p'

bind-key -n 'M-escape' copy-mode
# send this keys to 
# if-shell "$is_vim" 'send-keys C-='
bind-key -n 'M-a' select-pane -t !
bind-key -n 'M-t' resize-pane -Z
bind-key -n 'M-l' last-window
bind-key -n 'M-v' split-window -v -c "#{pane_current_path}"
bind-key -n 'M-h' split-window -h -c "#{pane_current_path}"
bind-key -n 'M-2' select-window -t :=2
bind-key -n 'M-3' select-window -t :=3
bind-key -n 'M-4' select-window -t :=4
bind-key -n 'M-5' select-window -t :=5
set -g mouse on
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'sainnhe/tmux-fzf'
set -g pane-active-border-style "bg=default fg=#fa9ebc"
set -g @plugin 'tmux-plugins/tmux-resurrect'

bind-key -r ^n next-window
bind-key -r ^p previous-window
bind-key -r ^s list-sessions -F '#{session_id}: #{session_name} (windows: #{session_windows}, attached: #{session_attached})'

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
# run '~/dotfiles/tmux/plugins/tpm/tpm'
